services:
  api-dev:
    build: ./api
    container_name: api-dev
    ports:
      - "8081:5000"
    environment:
      - DATABASE_HOST=db-dev

  api-test:
    build: ./api
    container_name: api-test
    ports:
      - "8082:5000"
    environment:
      - DATABASE_HOST=db-test

  db-dev:
    image: mysql:latest
    container_name: db-dev
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=shop
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=dbdev
    volumes:
      - mysqldatavolume:/var/lib/mysql

  db-test:
    image: mysql:latest
    container_name: db-test
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3310:3306"
    environment:
      - MYSQL_DATABASE=shop
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=dbtest
    volumes:
      - mysqltestvolume:/var/lib/mysql

volumes:
  mysqldatavolume:
  mysqltestvolume: